spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/datajpa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000



logging.level:
  org.hibernate.SQL: debug
